- file: Commonlove.webp
  title: Common Love
  author: LeanFries
  text: Flag representing an international association of 56 countries united
        by their shared history and love for Olivia Monroe
  type: International

- file: OliRSA.webp
  title: Oligarchy of South Africa
  author: LeanFries
  text: The flag of South Africa under the rule of Olivia Monroe and her chosen
        gal pals; their policies are driven by DFE and increasing birth rates.
  type: Africa
  coordinates: [-33.9221, 18.4231]

- file: oliun1v22.webp
  title: United Olivians
  author: Relishes
  text: Centre of the world? The North Pole? Paaaah! We know where it is!
  type: International

- file: theoliviarampant.webp
  title: The Olivia Rampant
  author: Relishes
  text: Our happy girl shows off her feisty side - Rampant, with hot pink
        stiletto nails, and shreds
  type: Europe
  coordinates: [55.066667, -6.000000]

- file: navi_ioc.webp
  title: International Olivia Committee
  author: Navi
  text: Every four years, ballet is the main event at the Olimpics. Officially,
        this is held at the Olisseum, but some say the grand finals are held in
        a "dungeon" deep underground
  type: International

- file: ninja_flag.webp
  title: The Fertile Crescent
  author: ninjasaurusrexatron
  text: 5 kids? There's no way you want 8 kids. 11 kids is too many. How are we
        supposed to take care of 15 kids?
  type: Asia
  coordinates: [37.887389, 41.132222]

- file: navi_oli_hood.webp
  title: Olivia Hood of Sherwood Forest
  author: Navi
  text: Legend has it that on Valentine's Day, Olivia Hood of Sherwood Forest
        stalks the woods in secret, marking unsuspecting single men with scented
        love arrows. Once struck, they are not claimed at once, but patiently
        savoured for a later time. Sherwood Forest is now a legendary attraction
        - particularly among the brave, the curious... and the single
  type: Europe
  coordinates: [53.207797736055355, -1.0844425546456038]

- file: Pink_USA.webp
  title: Stars and Stripes are in girl! 💅
  author: BingoBangoTangoMango
  text: Like States becoming united, we're all United by our love of Olivia
        Monroe
  type: International

- file: Flolivia.webp
  title: Flag of Flolivia
  author: BingoBangoTangoMango
  text: Olivia gotta be rep'n all us Flo peeps, yo.
  type: North America
  coordinates: [25.7742, -80.1936]
